# This file is for associating calibration data images with their
# intended functions.

[msl]
    [msl.mahli]
        flat = "MSL_MAHLI_FLAT_Sol2904_V1.png"
        inpaint_mask = "MSL_MAHLI_INPAINT_Sol2904_V1.png"
        mask = ""
        lut = "msl/ilut/DECOMPAND0.TXT"
    
    [msl.nav_right]
        flat = "MSL_NRB_FLAT_V1.png"
        inpaint_mask = "MSL_NRB_INPAINT_Sol3052_V1.png"
        mask = ""
        lut = ""
    
    [msl.nav_left]
        flat = "MSL_NLB_FLAT_V1.png"
        inpaint_mask = ""
        mask = ""

    [msl.fhaz_right]
        flat = "MSL_FRB_FLAT_V1.png"
        inpaint_mask = ""
        mask = ""
    
    [msl.fhaz_left]
        flat = "MSL_FLB_FLAT_V1.png"
        inpaint_mask = ""
        mask = ""

    [msl.rhaz_right]
        flat = "MSL_RRB_FLAT_V1.png"
        inpaint_mask = ""
        mask = ""

    [msl.rhaz_left]
        flat = "MSL_RLB_FLAT_V1.png"
        inpaint_mask = ""
        mask = ""

    [msl.mastcam_right]
        flat = "FLAT_MR_filter0_0-rjcal.jpg"
        inpaint_mask = "MSL_MCAM_RIGHT_INPAINT_Sol3101_V1.png"
        mask = ""
        lut = "msl/ilut/DECOMPAND0.TXT"

    [msl.mastcam_left]
        flat = "FLAT_ML_filter0_0-rjcal.jpg"
        inpaint_mask = "MSL_MCAM_LEFT_INPAINT_Sol3082_V1.png"
        mask = ""
        lut = "msl/ilut/DECOMPAND0.TXT"

    [msl.chemcam]
        flat = "MSL_CCAM_FLAT_Sol32_V1.png"
        inpaint_mask = ""
        mask = "MSL_CCAM_MASK_Sol3122_V2.png"

    [msl.mardi]
        flat = "FLAT_MD_0_RGB_V1.jpg"
        inpaint_mask = ""
        mask = ""
        lut = "msl/ilut/DECOMPAND0.TXT"

[m20]
    [m20.mastcamz_right]
        flat = "R0_-motorcount-_cont_v1.jpg"
        inpaint_mask = "M20_MCZ_RIGHT_INPAINT_MASK_V1.png"
        mask = ""
        lut = "m20/ilut/M20_MCZ_LUT0.txt"
    
    [m20.mastcamz_left]
        flat = "L0_-motorcount-_cont_v1.jpg"
        inpaint_mask = "M20_MCZ_LEFT_INPAINT_MASK_V1.png"
        mask = ""
        lut = "m20/ilut/M20_MCZ_LUT0.txt"

    [m20.watson]
        flat = "M20_WATSON_PREFLIGHT_FLAT_RGB_FOCUS_11958_V1.jpg"
        inpaint_mask = "M20_WATSON_INPAINT_MASK_V1.png"
        mask = ""
        lut = "m20/ilut/M20_SI_LUT0.txt"

    [m20.supercam_rmi]
        flat = "M20_RMI_PREFLIGHT_FOD_V1.jpg"
        inpaint_mask = ""
        mask = "M20_SCAM_MASK_Sol1_V1.png"
        lut = "m20/ilut/M20_COMP_LUT0.txt"

    [m20.nav_left]
        flat = "FM103_flat_rgb_bias_mask.jpg"
        inpaint_mask = ""
        mask = "FM103_mask.jpg"
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.nav_right]
        flat = "FM103_flat_rgb_bias_mask.jpg"
        inpaint_mask = ""
        mask = "FM103_mask.jpg"
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.fhaz_right]
        flat = "FM110_flat_rgb_bias.jpg"
        inpaint_mask = ""
        mask = ""
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.fhaz_left]
        flat = "FM105_flat_rgb_bias.jpg"
        inpaint_mask = ""
        mask = ""
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.rhaz_right]
        flat = "FM111_flat_rgb_bias.jpg"
        inpaint_mask = ""
        mask = ""
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.rhaz_left]
        flat = "FM108_flat_rgb_bias.jpg"
        inpaint_mask = ""
        mask = ""
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.pixl_mcc]
        flat = "M20_FLAT_SN_5001.jpg"
        inpaint_mask = ""
        mask = ""

    [m20.skycam]
        flat = "meda_rad_flat_padded.jpg"
        inpaint_mask = ""
        mask = ""

    [m20.heli_nav]
        flat = "M20_HELI_NAV_FLAT_Sol76_V1.jpg"
        inpaint_mask = ""
        mask = ""

    [m20.heli_rte]
        flat = "M20_HELI_RTE_FLAT_V3.png"
        inpaint_mask = ""
        mask = ""

    [m20.sherloc_aci]
        flat = "SHERLOC_ACI_Sol0077_Flat.png"
        inpaint_mask = ""
        mask =""

    [m20.cachecam]
        flat = ""
        inpaint_mask = ""
        mask = ""
        lut = "m20/ilut/M20_LUT2_v2a.txt"

    [m20.edl_rdcam]
        flat = ""
        inpaint_mask = ""
        mask = ""

[nsyt]
    [nsyt.idc]
        flat = "NSYT_FLAT_SN_0210.jpg"
        lut = "nsyt/ilut/NSYT_LUT0.txt"

    [nsyt.icc]
        flat = "NSYT_FLAT_SN_0203.jpg"
        lut = "nsyt/ilut/NSYT_LUT0.txt"



