calfiletype = "profile"
apply_ilt = false
red_scalar = 1.237
green_scalar = 1.0
blue_scalar = 0.802
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
filename_suffix = "rjcal-rad"
mission = "Mars2020"
instrument = "HELI-RTE"
description = ""