calfiletype = "profile"
apply_ilt = true
red_scalar = 1.05
green_scalar = 0.88
blue_scalar = 1.08
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
filename_suffix = "rjcal-drcx"
mission = "Mars2020"
instrument = "Navcam"
description = ""
srgb_color_correction = true