calfiletype = "profile"
apply_ilt = true
red_scalar = 0.9746
green_scalar = 0.991
blue_scalar = 1.9515
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
filename_suffix = "rjcal-rad"
mission = "Mars2020"
instrument = "CACHECAM"
description = ""