calfiletype = "profile"
apply_ilt = true
red_scalar = 1.0
green_scalar = 1.0
blue_scalar = 1.0
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
filename_suffix = "rjcal-ilt"
mission = "Mars2020"
instrument = "Navcam"
description = ""