calfiletype = "profile"
apply_ilt = true
red_scalar = 1.0
green_scalar = 0.96
blue_scalar = 1.2095
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
srgb_color_correction = true
filename_suffix = "rjcal-drcx"
mission = "Mars2020"
instrument = "WATSON"
description = ""
