apply_ilt = true
red_scalar = 0.9029
green_scalar = 0.9238
blue_scalar = 1.25
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
filename_suffix = "rjcal-cb2"