calfiletype = "profile"
apply_ilt = true
red_scalar = 1.0
green_scalar = 0.924
blue_scalar = 0.9768
color_noise_reduction = false
color_noise_reduction_amount = 0
hot_pixel_detection_threshold = 0
filename_suffix = "rjcal-drcx"
mission = "Mars2020"
instrument = "MASTCAMZ"
description = ""
srgb_color_correction = true